apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.10.1         # Check for the latest version!
    releaseName: my-nginx
    valuesInline:
      controller:
        replicaCount: 1
