apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

helmCharts:
  - name: nginx
    repo: https://nginxinc.github.io/helm-charts
    version: 0.18.0
    releaseName: my-nginx
    valuesFile: values.yaml    
