apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nginx
    repo: https://charts.bitnami.com/bitnami   # Example Helm repository
    version: 15.3.4                            # You can pin your desired version
    releaseName: my-nginx                      # Name to use for the Helm release
    valuesInline:                              # Optionally override chart values
      service:
        type: ClusterIP
    namespace: default                         # Change as needed
