apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

helmCharts:
  - name: nginx
    repo: https://charts.bitnami.com/bitnami
    version: 15.3.4  # Make sure this chart version exists
    releaseName: my-nginx
    valuesInline:
      service:
        type: ClusterIP
      image:
        tag: 1.25.2-debian-11-r56  # <-- Use a valid tag from Docker Hub
