apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

helmCharts:
  - name: nginx
    repo: https://charts.bitnami.com/bitnami
    version: 15.3.4
    releaseName: my-nginx
    valuesInline:
      service:
        type: ClusterIP
      image:
        registry: docker.io
        repository: nginx        # <-- NOTE: official nginx image
        tag: latest
